blank_issues_enabled: false
contact_links:
  - name: Azure CLI Product Feedback
    url: https://github.com/Azure/azure-cli/issues/new/choose
    about: Please open issues and feature requests for current Azure CLI here.
