name: Documentation issue report 🐛
description: Report an issue with current documentation.
labels:
  - needs-triage
  - doc-bug
body:
- type: markdown
  attributes:
    value: |
      Use this template to report issues with documentation. This can include typos,
      technical and factual errors, grammar, spelling, formatting, presentation, etc.
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: Write a descriptive title.
      required: true
    - label: Search the existing issues.
      required: true
    - label: I am reporting the documentation problem for the current version of Azure CLI.
      required: true
- type: input
  attributes:
    label: Azure CLI version being used
    placeholder: Run "az --version" in your terminal for your version. E.g. 2.30.0
  validations:
    required: true
- type: input
  attributes:
    label: Link to affected document
    placeholder: Enter a GitHub or Docs URL to the article.
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of the documentation error
    description: >
      Describe the error in the documentation. Include details about what you this is wrong.
    placeholder: |
      Example 3 has invalid parameters.

      List of steps, sample code, or failing test to support your claim.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggested fix
    description: >
      How would you change the document to make it correct.
  validations:
    required: false
